name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add LLVM APT repository
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key \
            | sudo apt-key add -
          DISTRO=$(lsb_release -cs)
          echo "deb http://apt.llvm.org/${DISTRO}/ llvm-toolchain-${DISTRO}-16 main" \
            | sudo tee /etc/apt/sources.list.d/llvm.list

      - name: Install LLVM 16 & Clang 16
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            llvm-16 llvm-16-dev clang-16 libclang-16-dev

      - name: Setup Haskell
        uses: haskell-actions/setup@v2.8.0
        with:
          ghc-version: '9.12.2'
          cabal-version: '3.14'

      - name: Update Cabal package list
        run: cabal update

      - name: Build library and executable
        run: cabal build --enable-tests

      - name: Run tests
        run: cabal test --test-show-details=direct

